{application,chat_tutorial,
             [{registered,[]},
              {description,"chat_tutorial"},
              {vsn,"0.0.1"},
              {modules,['Elixir.ChatMailbox.Message',
                        'Elixir.ChatMailbox.State','Elixir.ChatMailbox',
                        'Elixir.ChatPostOffice.State','Elixir.ChatPostOffice',
                        'Elixir.ChatTutorial']},
              {applications,[kernel,stdlib,elixir]}]}.